# Generated by Django 6.1.1 on 2026-09-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('Category', models.CharField(max_length=32, verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
